### ISSUE TITLE
Missing Source Code

### ISSUE THREAD

**Issue by CodeOfMarius** [PacktPublishing/Java-EE-8-Microservices#1]
Hello,
I recently purchased th "Java-EE-8-Microservices" Book from Packt Publishing and I was looking for the example Sourcecode here. But most of the Chapters only have the pom-files and not the actual Sourcecode. Am I missing something here?

**Comment by MurtazaTinwala** [comment]
Hi @CodeOfMarius 

I can see the code files present in the repository.
This is the final code files provided by the authors.
Please open again in case of any issues. 

Regards,

**Comment by kassapoglou** [comment]
The files are NOT in the repository. The previous user was correct about this. Each project is incomplete. All Pacts' repositories include full code and complete projects per chapter. On this book this is not the case. So please fix this problem and present a complete example per chapter as it is hard to actually end up with a working example at the end of each chapter because it refers to classes and files that do not exist!
